# Generated by Django 4.1.3 on 2023-01-03 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videojuegoapp', '0002_remove_post_subtitulo_autor_user_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
