# Generated by Django 4.1.3 on 2023-01-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegoapp', '0004_remove_autor_apellido_remove_autor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='imagen_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
